# Generated by Django 5.0.4 on 2024-07-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockEzyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('histid', models.AutoField(db_column='HistID', primary_key=True, serialize=False)),
                ('open', models.CharField(db_column='Open', max_length=100)),
                ('high', models.CharField(db_column='High', max_length=100)),
                ('low', models.CharField(db_column='Low', max_length=100)),
                ('volume', models.CharField(db_column='Volume', max_length=100)),
                ('close', models.CharField(db_column='Close', max_length=100)),
                ('custid', models.ForeignKey(db_column='CustID', on_delete=django.db.models.deletion.CASCADE, to='StockEzyApp.customers')),
            ],
            options={
                'db_table': 'history',
                'managed': True,
            },
        ),
    ]
